services:
  - type: web
    name: janata-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: DB_HOST
        value: dpg-d3ikkkk9c44c73aslfmg-a
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: janata_report
      - key: DB_USER
        value: postgres_admin
      - key: DB_PASSWORD
        value: Wdlcl1JxA9hQI4rxWYbd7E9wiwJXAIuq
